version: "3"

services:
  python:
    image: sample-python-container:latest
    ports:
      - 8080:5000
    restart: unless-stopped
    env_file:
      - ~/.aws/credentials
    environment:
      - ENV=local