FROM python:3.8-slim

RUN apt-get clean && apt-get -y update

RUN apt-get -y install python3-dev build-essential

WORKDIR /srv/flask_app/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# COPY . .
COPY . /srv/flask_app

CMD [ "python", "./main.py" ]